#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/task_agile_test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#  logging:
#    level:
#      org.hibernate.type.descriptor.sql: trace

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/oauthTest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#  h2:
#    console:
#      enabled: true
#      path: /console
#  thymeleaf:
#    cache: false

spring:
  datasource:
    url: jdbc:h2:~/oauthTest
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    user:
      name: user
      password: test
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

springfox:
  documnetation:
    auto-startup: false